name: Update Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza a cada 24 horas
  workflow_dispatch:

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user: joaomonferrari
          svg_out_path: .github/PROFILE-SNAKE.svg
          style: 'flat-square'
    
      - name: Commit Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/PROFILE-SNAKE.svg'
          message: 'Update snake svg'
